#!/usr/bin/env bash
# pocket-dev installer
#
# One-liner install (from fresh VPS):
#   curl -fsSL https://raw.githubusercontent.com/jpjednorski/pocket-dev/master/install.sh | \
#     TAILSCALE_AUTH_KEY=tskey-xxx NTFY_TOPIC=my-secret-topic bash
#
# Or clone first:
#   git clone <repo> ~/.pocket-dev && cd ~/.pocket-dev && ./install.sh

set -eo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

REPO_URL="${POCKET_DEV_REPO:-https://github.com/jpjednorski/pocket-dev.git}"
INSTALL_DIR="${POCKET_DEV_DIR:-$HOME/.pocket-dev}"

echo ""
echo -e "${BLUE}${BOLD}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}${BOLD}║          📱 pocket-dev installer       ║${NC}"
echo -e "${BLUE}${BOLD}╚════════════════════════════════════════╝${NC}"
echo ""

SCRIPT_DIR=""
if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd 2>/dev/null)" || SCRIPT_DIR=""
fi

if [[ -n "$SCRIPT_DIR" && -f "$SCRIPT_DIR/justfile" ]]; then
    echo -e "${GREEN}▸${NC} Running from cloned repository"
    INSTALL_DIR="$SCRIPT_DIR"
else
    # Running via curl - clone the repo first
    echo -e "${BLUE}▸${NC} Running via curl/wget"
    
    # Check if env vars are provided for one-liner install
    if [[ -z "${TAILSCALE_AUTH_KEY:-}" || -z "${NTFY_TOPIC:-}" ]]; then
        echo ""
        echo -e "${YELLOW}════════════════════════════════════════════════${NC}"
        echo -e "${YELLOW}  One-liner install requires env vars${NC}"
        echo -e "${YELLOW}════════════════════════════════════════════════${NC}"
        echo ""
        echo "Usage:"
        echo ""
        echo -e "  ${BOLD}curl -fsSL <install-url> | \\"
        echo -e "    TAILSCALE_AUTH_KEY=tskey-xxx NTFY_TOPIC=my-topic bash${NC}"
        echo ""
        echo "Or clone first:"
        echo ""
        echo -e "  ${BOLD}git clone $REPO_URL ~/.pocket-dev${NC}"
        echo -e "  ${BOLD}cd ~/.pocket-dev && cp .env.example .env${NC}"
        echo -e "  ${BOLD}# edit .env${NC}"
        echo -e "  ${BOLD}./install.sh${NC}"
        echo ""
        echo "Required env vars:"
        echo "  TAILSCALE_AUTH_KEY  - https://login.tailscale.com/admin/settings/keys"
        echo "  NTFY_TOPIC          - Pick a secret topic name"
        echo ""
        exit 1
    fi
    
    # Clone repo
    echo -e "${BLUE}▸${NC} Cloning pocket-dev..."
    if [[ -d "$INSTALL_DIR" ]]; then
        echo -e "${YELLOW}▸${NC} $INSTALL_DIR exists, updating..."
        cd "$INSTALL_DIR"
        git pull --ff-only || true
    else
        git clone "$REPO_URL" "$INSTALL_DIR"
    fi
fi

export POCKET_DEV_DIR="$INSTALL_DIR"
cd "$INSTALL_DIR"

# Create .env from env vars if provided, otherwise check for existing .env
if [[ -n "${TAILSCALE_AUTH_KEY:-}" && -n "${NTFY_TOPIC:-}" ]]; then
    # Env vars provided - create/update .env
    echo -e "${BLUE}▸${NC} Creating .env from provided env vars..."
    cat > .env <<EOF
# Generated by pocket-dev installer
TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY}
NTFY_TOPIC=${NTFY_TOPIC}
EOF
    # Add optional vars if provided
    [[ -n "${HETZNER_API_TOKEN:-}" ]] && echo "HETZNER_API_TOKEN=${HETZNER_API_TOKEN}" >> .env
    [[ -n "${GITHUB_TOKEN:-}" ]] && echo "GITHUB_TOKEN=${GITHUB_TOKEN}" >> .env
elif [[ ! -f .env ]]; then
    # No env vars and no .env file - prompt for manual setup
    echo -e "${YELLOW}▸${NC} Creating .env from template..."
    cp .env.example .env
    echo ""
    echo -e "${YELLOW}════════════════════════════════════════════════${NC}"
    echo -e "${YELLOW}  ⚠️  Configuration required${NC}"
    echo -e "${YELLOW}════════════════════════════════════════════════${NC}"
    echo ""
    echo "Edit $INSTALL_DIR/.env with your settings:"
    echo ""
    echo "  Required:"
    echo "    TAILSCALE_AUTH_KEY  - Get from https://login.tailscale.com/admin/settings/keys"
    echo "                          (Create a reusable, ephemeral key)"
    echo "    NTFY_TOPIC          - Pick a secret topic name (e.g., pocket-dev-abc123)"
    echo ""
    echo "Then run:"
    echo -e "  ${BOLD}cd $INSTALL_DIR && just install${NC}"
    echo ""
    exit 0
fi

# Load and validate env vars
source .env

if [[ -z "${TAILSCALE_AUTH_KEY:-}" ]]; then
    echo -e "${RED}✗${NC} TAILSCALE_AUTH_KEY not set in .env"
    echo "  Get one from: https://login.tailscale.com/admin/settings/keys"
    exit 1
fi

if [[ -z "${NTFY_TOPIC:-}" ]]; then
    echo -e "${RED}✗${NC} NTFY_TOPIC not set in .env"
    echo "  Pick a secret topic name for push notifications"
    exit 1
fi

if ! command -v just &>/dev/null; then
    echo -e "${BLUE}▸${NC} Installing just..."
    curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin 2>/dev/null || {
        mkdir -p "$HOME/.local/bin"
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to "$HOME/.local/bin"
        export PATH="$HOME/.local/bin:$PATH"
    }
fi

cd "$INSTALL_DIR"
just install
